### ISSUE TITLE
Non usare abbreviazioni nel titolo, scrivilo per esteso

### ISSUE THREAD

**Issue by EnricoGiampieri** [DavideSangiorgi/TesiCNNs#9]
https://github.com/DavideSangiorgi/TesiCNNs/blob/aceb3ae171eee20da58647179c2cf9b689064b24/stesura/Tesi_1_09.tex#L46

**Comment by DavideSangiorgi** [comment]
il titolo adesso è scritto per esteso. Come faccio a distanziare le righe in cui è scritto il titolo?
